Hausaufgaben2 - Giang Bich Ngoc - s0575811
ProfWider/tdd-setup pull request #17
Opened 2020-10-22 20:29 UTC by Biiichngoooc

2020-10-25 21:44 UTC, ProfWider requested changes
Die drei neuen Testfälle sind super, aber es fehlen noch die Bugfixes in der Calculator-Klasse!
Das können Sie u.a. auch daran sehen, dass unter Ihrem PR der Travis Check fehlschlägt https://travis-ci.com/github/ProfWider/tdd-setup/builds/192559762. Travis ist ein Build-Server, der genau wie bei Ihnen lokal die Tests mit Gradle ausführt und fehlschlägt, wenn die Tests nicht alle grün sind.
Sie müssen Änderungen in der Datei Calculator.java vornehmen, so dass all Ihre Tests grün werden, und zwar ohne die Tests dabei zu ändern, und diese Änderungen in zwei neue Commits verpacken, die Sie dann einfach zu dem bestehenden PR hinzufügen können. Führen Sie aber vorher gradle test lokal bei sich aus und prüfen Sie ob alles grün wird.

2020-10-29 17:03 UTC, Biiichngoooc commented
Ich habe meine Aufgabe geändert. Alles war grün :)

2020-10-29 17:04 UTC, ProfWider approved these changes
das sieht besser aus! Die Minimalanforderungen sind erfüllt insofern erstmal bestanden 👍 
Aber die ganze Commit-Struktur ist jetzt wirklich sehr unübersichtlich geworden durch die zusätzlichen Commits. Insofern würde ich Sie bitten doch vielleicht einfach nochmal neu zu forken, clonen, und dann Stück für Stück die Änderungen rüber zu ziehen und dabei jeweils saubere Commits zu erzeugen, und dann einen neuen PR zu stellen. Da Sie die eigentliche Lösung ja jetzt schon haben sollte das auch schnell gemacht sein.

2020-10-29 17:24 UTC, Biiichngoooc commented
Wie kann ich neu clone forken ? Ich hab wie letzter Mal geforkt aber es geht nicht

2020-10-29 17:27 UTC, ProfWider commented
Man muss zuerst das eigene Repository löschen (bei Settings und dann ganz unten Danger Zone). Dann kann man auch wieder neu forken und neu klonen. Nur darauf achten lokal dann in einen anderen Ordner zu clonen, damit Sie ihre bisherigen Änderungen noch lokal da haben um sie rüber kopieren zu können.

2020-10-29 19:50 UTC, closed without merging