Hausaufgabe2_S0574551
ProfWider/tdd-setup pull request #73
Opened 2020-10-29 20:00 UTC by Lauramuecke

2020-10-29 20:25 UTC, ProfWider requested changes
Die Commit-Struktur ist super und schön sauber 👍 
Die folgende Anforderung ist aber noch nicht erfüllt: "Schreiben Sie zwei neue zusätzliche Tests, die zwei unterschiedliche Fehler in zwei unterschiedlichen Methoden aufdecken (d.h. Kombinationen von unterschiedliche Methoden testen) und somit fehlschlagen. Da die Kombination pressOperationKey, pressDigitKey, pressEquals schon getestet ist, sollte also noch mindestens eine der Methoden pressClear, pressDotKey, oder pressNegative getestet werden."
Erstens verwenden Sie in Ihren roten Tests keine dieser 3 Methoden, und 2. decken Sie hier eigentlich keine Fehler auf: Beim ersten Test+Bugfix fügen Sie eine neue Funktionalität hinzu (das würde ich, wie bei anderen, noch akzeptieren), aber der zweite Fall macht keinen Sinn, wenn man den Online-Calculator betrachtet. Dort kann man, wenn man eine der Zahlentasten (digit key) drückt, auch immer nur eine Ziffer von 0-9 hinzufügen. Wenn dann müssten Sie schon einen Test mit pressDigitKey(1), pressDigitKey(0), etc. schreiben. Aber auch dann würde noch ein roter Test mit pressDot, pressClear oder pressNegative fehlen. Also fügen Sie am besten einfach einen solchen inkl. Bugfix hinzu. Sie können die entsprechenden zwei Commits einfach zu diesem bestehenden PR hinzufügen.

2020-10-30 14:18 UTC, ProfWider requested changes
Der neue Test sieht schon mal gut aus: er ist aus den richtigen Gründen rot (d.h. er deckt einen Fehler auf) und er entspricht den Anforderungen. Wenn sie jetzt noch den passenden Bugfix liefern haben Sie bestanden 👍

2020-10-30 15:24 UTC, Lauramuecke commented
Also das mit den commits habe ich jetzt versaut, aber commits zu löschen hat mich irgendwie abgeschreckt und ich probiere es lieber nicht an der Hausaufgabe aus. :( Das commit "neuer roter Test" bitte ignorieren, denn ich habe genau was anderes gepusht. Ich hoffe es passt trotzdem alles. :D

2020-10-30 15:58 UTC, ProfWider approved these changes
Ja, "Bugfix neuer richtiger roter Test" ist schon eine interessante Commit Nachricht :-)
Aber Travis ist zufrieden und damit bin ich es auch. Bestanden 👍 
Wie bei den anderen auch: jetzt, wo der Druck weg ist, können Sie ja überlegen, ob Sie nochmal neu forken, clonen, saubere Commits erzeugen, und dann einen neuen PR stellen.

2020-10-31 10:59 UTC, Lauramuecke commented
Das mache ich noch. Übung macht den Meister. 😅

2020-10-31 16:19 UTC, closed without merging