master
ProfWider/tdd-setup pull request #77
Opened 2020-10-30 19:56 UTC by salemraffa

2020-10-30 20:13 UTC, ProfWider requested changes
Von den 7 Tests sind leider noch 5 rot, wenn ich das lokal bei mir mit `gradle test` ausführe.
Am Ende müssen alle Tests grün sein (d.h. alle Tests und Bugfixes müssen zusammen funkionieren).
Führen Sie lokal bei sich `gradle test` aus bevor Sie pushen, und probieren Sie so lange Bugfixes zu implementieren bis alles grün ist.
Allerdings brauchen Sie überhaupt nicht so viele Tests, 3 reichen: z.B. der mit der Multiplikation, der eh funktioniert, dann noch einer mit pressDotKey, und z.B. noch einer mit pressNegative. Wenn Sie zu viele Tests gleichzeitig versuchen zu fixen, wird Sie das sehr verwirren.
Noch eine Anmerkung: eine negative oder mehrstellige Zahl an die Methode pressOperationKey zu übergeben macht eigentlich nicht so viel Sinn, weil man das ja im Online-Calculator auch nicht kann: man kann mit einem Tastendruck auch immer nur eine positive Ziffer eingeben.

2020-10-30 23:01 UTC, salemraffa commented
ich sitze jetzt schon seit 9 Stunden dran und schaffe es nicht mit dem
Bugfix bzw. die Tests grün zu machen.
Ich schaffe es auch nicht eine zweite Pull request zu erstellen aber es
gibt keinen riesigen unterschied zwischen beiden.
Mir sind die Hände gebunden, da ich auch  die letzte Woche die Übung
verpasst habe und die heutige nicht stattgefunden hat.
Ich hoffe es Ihnen reicht die erste pull request obwohl es unvollständig
ist.

Guten Abend
Salem Rafaf

On Fri, Oct 30, 2020 at 9:13 PM Prof. Dr. Arif Wider <
notifications@github.com> wrote:

> *@ProfWider* requested changes on this pull request.
>
> Von den 7 Tests sind leider noch 5 rot, wenn ich das lokal bei mir mit gradle
> test ausführe.
> Am Ende müssen alle Tests grün sein (d.h. alle Tests und Bugfixes müssen
> zusammen funkionieren).
> Führen Sie lokal bei sich gradle test aus bevor Sie pushen, und probieren
> Sie so lange Bugfixes zu implementieren bis alles grün ist.
> Allerdings brauchen Sie überhaupt nicht so viele Tests, 3 reichen: z.B.
> der mit der Multiplikation, der eh funktioniert, dann noch einer mit
> pressDotKey, und z.B. noch einer mit pressNegative. Wenn Sie zu viele Tests
> gleichzeitig versuchen zu fixen, wird Sie das sehr verwirren.
> Noch eine Anmerkung: eine negative oder mehrstellige Zahl an die Methode
> pressOperationKey zu übergeben macht eigentlich nicht so viel Sinn, weil
> man das ja im Online-Calculator auch nicht kann: man kann mit einem
> Tastendruck auch immer nur eine positive Ziffer eingeben.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProfWider/tdd-setup/pull/77#pullrequestreview-521003643>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARMBGGFGKMMGOEHYWUUBEOLSNMNAJANCNFSM4TFLYK7Q>
> .
>

2020-10-30 23:04 UTC, salemraffa commented
Hier noch die Screenshots vom erweiterten Projekt.

On Sat, Oct 31, 2020 at 12:01 AM salem raffa <salembraffa@gmail.com> wrote:

> ich sitze jetzt schon seit 9 Stunden dran und schaffe es nicht mit dem
> Bugfix bzw. die Tests grün zu machen.
> Ich schaffe es auch nicht eine zweite Pull request zu erstellen aber es
> gibt keinen riesigen unterschied zwischen beiden.
> Mir sind die Hände gebunden, da ich auch  die letzte Woche die Übung
> verpasst habe und die heutige nicht stattgefunden hat.
> Ich hoffe es Ihnen reicht die erste pull request obwohl es unvollständig
> ist.
>
> Guten Abend
> Salem Rafaf
>
> On Fri, Oct 30, 2020 at 9:13 PM Prof. Dr. Arif Wider <
> notifications@github.com> wrote:
>
>> *@ProfWider* requested changes on this pull request.
>>
>> Von den 7 Tests sind leider noch 5 rot, wenn ich das lokal bei mir mit gradle
>> test ausführe.
>> Am Ende müssen alle Tests grün sein (d.h. alle Tests und Bugfixes müssen
>> zusammen funkionieren).
>> Führen Sie lokal bei sich gradle test aus bevor Sie pushen, und
>> probieren Sie so lange Bugfixes zu implementieren bis alles grün ist.
>> Allerdings brauchen Sie überhaupt nicht so viele Tests, 3 reichen: z.B.
>> der mit der Multiplikation, der eh funktioniert, dann noch einer mit
>> pressDotKey, und z.B. noch einer mit pressNegative. Wenn Sie zu viele Tests
>> gleichzeitig versuchen zu fixen, wird Sie das sehr verwirren.
>> Noch eine Anmerkung: eine negative oder mehrstellige Zahl an die Methode
>> pressOperationKey zu übergeben macht eigentlich nicht so viel Sinn, weil
>> man das ja im Online-Calculator auch nicht kann: man kann mit einem
>> Tastendruck auch immer nur eine positive Ziffer eingeben.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ProfWider/tdd-setup/pull/77#pullrequestreview-521003643>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARMBGGFGKMMGOEHYWUUBEOLSNMNAJANCNFSM4TFLYK7Q>
>> .
>>
>

2020-10-30 23:11 UTC, ProfWider requested changes
Sie brauchen keinen neuen PR erstellen - nachdem Sie weitere Commits auf Ihr geforktes Repository gespusht haben, bietet Ihnen GitHub an, diese neuen Commits zu dem bestehenden PR hinzuzufügen. Das wäre in Ordnung, sofern denn alle Tests (bei Ihnen lokal und bei Travis) grün werden. Sie haben ja jetzt noch bis morgen (Samstag) Abend Zeit, das zu fixen.

2020-10-31 16:12 UTC, ProfWider requested changes
fast: noch steht 0.4 statt 2 auf Ihrem "display", wie Sie hier sehen können: https://travis-ci.com/github/ProfWider/tdd-setup/builds/196950794 (das Ergenbis, wenn Sie lokal gradle test ausführen sollte aber immer genau das gleiche sein wie bei Travis).
Das sieht mir eigentlich nach einem eher kleinen Fehler aus - das können Sie noch schaffen!

2020-11-01 15:06 UTC, salemraffa commented
ich habe es nicht geschafft die Lösung zu finden aber die Aufgabe ist fast richtig. Kann ich mich an der Klausur noch anmelden ?

2022-04-20 13:19 UTC, closed without merging